[book]
title = "html mermaid example"
description = "An example book that embeds a mermaid diagram using the html renderer"
authors = ["Kenton Hamaluik"]
language = "en"

[preprocessor.diagrams]
output_format = "png"
kroki_url = "https://kroki.io"
language_prefix = ""
kroki_timeout_sec = 5
filename_prefix = "diagram-"

[preprocessor.diagrams.diagram_options]
theme = "forest"
look = "handDrawn"
